"Hello Jenkins Learner!"
"Added a webhook this time!"
"forgot to add /github-webhook/ part then added"
"jenkins plugin added this time"
"test the webhook again after restart Jenkins server"
"git link added Source Code MAnagement Tab instead of General Tab in Jenkins new item menu"
